add brotli decompression #312
tested and working: new m4/ax_check_brotlilib.m4, updated autotools; updated ugrep.cpp

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -777,6 +777,7 @@ with_bzlib
 with_lzma
 with_lz4
 with_zstd
+with_brotlilib
 with_grep_path
 with_grep_colors
 enable_auto_color
@@ -1476,6 +1477,10 @@ Optional Packages:
   --with-zstd=DIR         root directory path of zstd installation [defaults to
                           /usr/local or /usr if not found in /usr/local]
   --without-zstd          to disable zstd usage completely
+  --with-brotlilib=DIR    root directory path of brotli library installation
+                          [defaults to /usr/local or /usr if not found in
+                          /usr/local]
+  --without-brotlilib     to disable brotli library usage completely
   --with-grep-path=GREP_PATH
                           specifies the GREP_PATH if different than the
                           default DATAROOTDIR/ugrep/patterns
@@ -8356,6 +8361,139 @@ printf "%s\n" "#define HAVE_LIBZSTD 1" >>confdefs.h
     # If either header or library was not found, action-if-not-found
     #
     echo "libzstd not found: ugrep option -z won't decompress .zst files"
+  fi
+fi
+
+
+#
+# Handle user hints
+#
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking if brotlilib is wanted" >&5
+printf %s "checking if brotlilib is wanted... " >&6; }
+brotlilib_places="/usr/local /usr /opt/homebrew /opt/local /sw"
+
+# Check whether --with-brotlilib was given.
+if test ${with_brotlilib+y}
+then :
+  withval=$with_brotlilib; if test "$withval" != "no" ; then
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+printf "%s\n" "yes" >&6; }
+  if test -d "$withval"
+  then
+    brotlilib_places="$withval $brotlilib_places"
+  else
+    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: Sorry, $withval does not exist, checking usual places" >&5
+printf "%s\n" "$as_me: WARNING: Sorry, $withval does not exist, checking usual places" >&2;}
+  fi
+else
+  brotlilib_places=""
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
+printf "%s\n" "no" >&6; }
+fi
+else $as_nop
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+printf "%s\n" "yes" >&6; }
+fi
+
+#
+# Locate brotlilib, if wanted
+#
+if test -n "${brotlilib_places}"
+then
+  # check the user supplied or any other more or less 'standard' place:
+  #   Most UNIX systems      : /usr/local and /usr
+  #   MacPorts / Fink on OSX : /opt/local respectively /sw
+  for BROTLILIB_HOME in ${brotlilib_places} ; do
+    if test -f "${BROTLILIB_HOME}/include/brotli/decode.h"; then break; fi
+    BROTLILIB_HOME=""
+  done
+
+  BROTLILIB_OLD_LDFLAGS=$LDFLAGS
+  BROTLILIB_OLD_CPPFLAGS=$CPPFLAGS
+  if test -n "${BROTLILIB_HOME}"; then
+    LDFLAGS="$LDFLAGS -L${BROTLILIB_HOME}/lib"
+    CPPFLAGS="$CPPFLAGS -I${BROTLILIB_HOME}/include"
+  fi
+  ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for BrotliDecoderCreateInstance in -lbrotlidec" >&5
+printf %s "checking for BrotliDecoderCreateInstance in -lbrotlidec... " >&6; }
+if test ${ac_cv_lib_brotlidec_BrotliDecoderCreateInstance+y}
+then :
+  printf %s "(cached) " >&6
+else $as_nop
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lbrotlidec  $LIBS"
+cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+char BrotliDecoderCreateInstance ();
+int
+main (void)
+{
+return BrotliDecoderCreateInstance ();
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_link "$LINENO"
+then :
+  ac_cv_lib_brotlidec_BrotliDecoderCreateInstance=yes
+else $as_nop
+  ac_cv_lib_brotlidec_BrotliDecoderCreateInstance=no
+fi
+rm -f core conftest.err conftest.$ac_objext conftest.beam \
+    conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_brotlidec_BrotliDecoderCreateInstance" >&5
+printf "%s\n" "$ac_cv_lib_brotlidec_BrotliDecoderCreateInstance" >&6; }
+if test "x$ac_cv_lib_brotlidec_BrotliDecoderCreateInstance" = xyes
+then :
+  brotlilib_cv_libbrotli=yes
+else $as_nop
+  brotlilib_cv_libbrotli=no
+fi
+
+  ac_fn_c_check_header_compile "$LINENO" "brotli/decode.h" "ac_cv_header_brotli_decode_h" "$ac_includes_default"
+if test "x$ac_cv_header_brotli_decode_h" = xyes
+then :
+  brotlilib_cv_brotli_h=yes
+else $as_nop
+  brotlilib_cv_brotli_h=no
+fi
+
+  ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+  if test "$brotlilib_cv_libbrotli" = "yes" && test "$brotlilib_cv_brotli_h" = "yes"
+  then
+    #
+    # If both library and header were found, action-if-found
+    #
+
+                CPPFLAGS="$CPPFLAGS -I${BROTLILIB_HOME}/include"
+                LDFLAGS="$LDFLAGS -L${BROTLILIB_HOME}/lib"
+                LIBS="-lbrotlidec -lbrotlienc $LIBS"
+
+printf "%s\n" "#define HAVE_LIBBROTLI 1" >>confdefs.h
+
+
+  else
+    #
+    # If either header or library was not found, action-if-not-found
+    #
+    echo "brotli library not found: ugrep option -z won't decompress .br files"
   fi
 fi
 
